In [1]:
#Task1:
import pandas as pd
import numpy  as np

In [2]:
df = pd.read_csv("/content/adult_with_headers (1).csv")
df

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education_num   32561 non-null  int64
 5   marital_status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital_gain    32561 non-null  int64
 11  capital_loss    32561 non-null  int64
 12  hours_per_week  32561 non-null  int64
 13  native_country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [4]:
#missing values
df.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

In [5]:
#in dataset there is no null values

In [6]:
#Apply scaling techniques to numerical features:
# a.Standard Scaling
num_col = df.select_dtypes(include=['int64','float64']).columns
num_col

Index(['age', 'fnlwgt', 'education_num', 'capital_gain', 'capital_loss',
       'hours_per_week'],
      dtype='object')

In [7]:
from sklearn.preprocessing import StandardScaler
std_sacler = StandardScaler()
df_standard_scaler = df.copy()
df_standard_scaler[num_col] = std_sacler.fit_transform(df[num_col])

In [8]:
df_standard_scaler[num_col]

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week
0,0.030671,-1.063611,1.134739,0.148453,-0.21666,-0.035429
1,0.837109,-1.008707,1.134739,-0.145920,-0.21666,-2.222153
2,-0.042642,0.245079,-0.420060,-0.145920,-0.21666,-0.035429
3,1.057047,0.425801,-1.197459,-0.145920,-0.21666,-0.035429
4,-0.775768,1.408176,1.134739,-0.145920,-0.21666,-0.035429
...,...,...,...,...,...,...
32556,-0.849080,0.639741,0.746039,-0.145920,-0.21666,-0.197409
32557,0.103983,-0.335433,-0.420060,-0.145920,-0.21666,-0.035429
32558,1.423610,-0.358777,-0.420060,-0.145920,-0.21666,-0.035429
32559,-1.215643,0.110960,-0.420060,-0.145920,-0.21666,-1.655225
32560,0.983734,0.929893,-0.420060,1.888424,-0.21666,-0.035429

In [9]:
#b. Min-Max Scaling
from sklearn.preprocessing import MinMaxScaler
minmax_scale = MinMaxScaler()
df_minmax_scale = df.copy()
df_minmax_scale[num_col] = minmax_scale.fit_transform(df[num_col])

In [10]:
df_minmax_scale[num_col]

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week
0,0.301370,0.044302,0.800000,0.021740,0.0,0.397959
1,0.452055,0.048238,0.800000,0.000000,0.0,0.122449
2,0.287671,0.138113,0.533333,0.000000,0.0,0.397959
3,0.493151,0.151068,0.400000,0.000000,0.0,0.397959
4,0.150685,0.221488,0.800000,0.000000,0.0,0.397959
...,...,...,...,...,...,...
32556,0.136986,0.166404,0.733333,0.000000,0.0,0.377551
32557,0.315068,0.096500,0.533333,0.000000,0.0,0.397959
32558,0.561644,0.094827,0.533333,0.000000,0.0,0.397959
32559,0.068493,0.128499,0.533333,0.000000,0.0,0.193878
32560,0.479452,0.187203,0.533333,0.150242,0.0,0.397959

In [11]:
#Discuss the scenarios where each scaling technique is preferred and why.
#:- StandardScaler we use When data follows a normal distribution. because it centers the data around 0 with unit variance.
#:- MinMaxScaler we use When data does not follow a normal distribution. because It preserves the original data distribution.

In [12]:
#Task2: Encoding Techniques:
#Apply One-Hot Encoding to categorical variables with less than 5 categories.
cat_col = df.select_dtypes(include=['object']).columns
cat_col

Index(['workclass', 'education', 'marital_status', 'occupation',
       'relationship', 'race', 'sex', 'native_country', 'income'],
      dtype='object')

In [13]:
one_hot_col = [col for col in cat_col if df[col].nunique() <= 5]
one_hot_col

['race', 'sex', 'income']

In [14]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(drop='first', sparse_output=False)
df_one_hot = encoder.fit_transform(df[one_hot_col])
df_one_hot = pd.DataFrame(df_one_hot, columns=encoder.get_feature_names_out(one_hot_col))

In [15]:
df_one_hot

,race_ Asian-Pac-Islander,race_ Black,race_ Other,race_ White,sex_ Male,income_ >50K
0,0.0,0.0,0.0,1.0,1.0,0.0
1,0.0,0.0,0.0,1.0,1.0,0.0
2,0.0,0.0,0.0,1.0,1.0,0.0
3,0.0,1.0,0.0,0.0,1.0,0.0
4,0.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...
32556,0.0,0.0,0.0,1.0,0.0,0.0
32557,0.0,0.0,0.0,1.0,1.0,1.0
32558,0.0,0.0,0.0,1.0,0.0,0.0
32559,0.0,0.0,0.0,1.0,1.0,0.0
32560,0.0,0.0,0.0,1.0,0.0,1.0

In [16]:
#Use Label Encoding for categorical variables
from sklearn.preprocessing import LabelEncoder
label_enc = LabelEncoder()
df_label_encoder = df.copy()

for col in cat_col:
    df_label_encoder[col] = label_enc.fit_transform(df_label_encoder[col])

In [17]:
df_label_encoder[cat_col]

,workclass,education,marital_status,occupation,relationship,race,sex,native_country,income
0,7,9,4,1,1,4,1,39,0
1,6,9,2,4,0,4,1,39,0
2,4,11,0,6,1,4,1,39,0
3,4,1,2,6,0,2,1,39,0
4,4,9,2,10,5,2,0,5,0
...,...,...,...,...,...,...,...,...,...
32556,4,7,2,13,5,4,0,39,0
32557,4,11,2,7,0,4,1,39,1
32558,4,11,6,1,4,4,0,39,0
32559,4,11,4,1,3,4,1,39,0
32560,5,11,2,4,5,4,0,39,1

In [18]:
#Load the dataset and conduct basic data exploration (summary statistics, missing values, data types).
df_final = pd.concat([df_standard_scaler[num_col], df_label_encoder[cat_col]], axis=1)

df_final

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week,workclass,education,marital_status,occupation,relationship,race,sex,native_country,income
0,0.030671,-1.063611,1.134739,0.148453,-0.21666,-0.035429,7,9,4,1,1,4,1,39,0
1,0.837109,-1.008707,1.134739,-0.145920,-0.21666,-2.222153,6,9,2,4,0,4,1,39,0
2,-0.042642,0.245079,-0.420060,-0.145920,-0.21666,-0.035429,4,11,0,6,1,4,1,39,0
3,1.057047,0.425801,-1.197459,-0.145920,-0.21666,-0.035429,4,1,2,6,0,2,1,39,0
4,-0.775768,1.408176,1.134739,-0.145920,-0.21666,-0.035429,4,9,2,10,5,2,0,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,-0.849080,0.639741,0.746039,-0.145920,-0.21666,-0.197409,4,7,2,13,5,4,0,39,0
32557,0.103983,-0.335433,-0.420060,-0.145920,-0.21666,-0.035429,4,11,2,7,0,4,1,39,1
32558,1.423610,-0.358777,-0.420060,-0.145920,-0.21666,-0.035429,4,11,6,1,4,4,0,39,0
32559,-1.215643,0.110960,-0.420060,-0.145920,-0.21666,-1.655225,4,11,4,1,3,4,1,39,0
32560,0.983734,0.929893,-0.420060,1.888424,-0.21666,-0.035429,5,11,2,4,5,4,0,39,1

In [19]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  float64
 1   fnlwgt          32561 non-null  float64
 2   education_num   32561 non-null  float64
 3   capital_gain    32561 non-null  float64
 4   capital_loss    32561 non-null  float64
 5   hours_per_week  32561 non-null  float64
 6   workclass       32561 non-null  int64
 7   education       32561 non-null  int64
 8   marital_status  32561 non-null  int64
 9   occupation      32561 non-null  int64
 10  relationship    32561 non-null  int64
 11  race            32561 non-null  int64
 12  sex             32561 non-null  int64
 13  native_country  32561 non-null  int64
 14  income          32561 non-null  int64
dtypes: float64(6), int64(9)
memory usage: 3.7 MB

In [20]:
#summary statistics
df_final.describe()

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week,workclass,education,marital_status,occupation,relationship,race,sex,native_country,income
count,3.256100e+04,3.256100e+04,3.256100e+04,3.256100e+04,3.256100e+04,3.256100e+04,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000
mean,-2.705915e-17,-1.001625e-16,1.471887e-16,1.309314e-17,1.016900e-16,-1.549355e-17,3.868892,10.298210,2.611836,6.572740,1.446362,3.665858,0.669205,36.718866,0.240810
std,1.000015e+00,1.000015e+00,1.000015e+00,1.000015e+00,1.000015e+00,1.000015e+00,1.455960,3.870264,1.506222,4.228857,1.606771,0.848806,0.470506,7.823782,0.427581
min,-1.582206e+00,-1.681631e+00,-3.529656e+00,-1.459205e-01,-2.166595e-01,-3.194030e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,-7.757679e-01,-6.816910e-01,-4.200596e-01,-1.459205e-01,-2.166595e-01,-3.542945e-02,4.000000,9.000000,2.000000,3.000000,0.000000,4.000000,0.000000,39.000000,0.000000
50%,-1.159546e-01,-1.082193e-01,-3.136003e-02,-1.459205e-01,-2.166595e-01,-3.542945e-02,4.000000,11.000000,2.000000,7.000000,1.000000,4.000000,1.000000,39.000000,0.000000
75%,6.904838e-01,4.478765e-01,7.460392e-01,-1.459205e-01,-2.166595e-01,3.695194e-01,4.000000,12.000000,4.000000,10.000000,3.000000,4.000000,1.000000,39.000000,0.000000
max,3.769612e+00,1.226856e+01,2.300838e+00,1.339458e+01,1.059351e+01,4.742967e+00,8.000000,15.000000,6.000000,14.000000,5.000000,4.000000,1.000000,41.000000,1.000000

In [21]:
#missing values
df_final.isnull().sum()

age               0
fnlwgt            0
education_num     0
capital_gain      0
capital_loss      0
hours_per_week    0
workclass         0
education         0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
native_country    0
income            0
dtype: int64

In [22]:
#data types
df_final.dtypes

age               float64
fnlwgt            float64
education_num     float64
capital_gain      float64
capital_loss      float64
hours_per_week    float64
workclass           int64
education           int64
marital_status      int64
occupation          int64
relationship        int64
race                int64
sex                 int64
native_country      int64
income              int64
dtype: object

In [23]:
#Discuss the pros and cons of One-Hot Encoding and Label Encoding.
#    One-Hot Encoding:- best for nominal data and it avoids ordinal relationships but increases dimensionality.
#    Label Encoding:- Efficient for tree-based models but may create false ordinal relationships between categories

In [24]:
#Task3: Feature Engineering:
#Create at least 2 new features that could be beneficial for the model. Explain the rationale behind your choices.
# Create new feature: Work Hours Category
def work_hours_category(hours):
    if hours < 30:
        return 'Part_Time'
    elif hours <= 40:
        return 'Full_Time'
    else:
        return 'Over_Time'

df['WorkHoursCategory'] = df['hours_per_week'].apply(work_hours_category)

# Create new feature: Age Group
def age_group(age):
    if age < 30:
        return 'Young'
    elif age < 50:
        return 'Middle_Aged'
    else:
        return 'Senior'

df['AgeGroup'] = df['age'].apply(age_group)

In [25]:
df[['age', 'AgeGroup', 'hours_per_week', 'WorkHoursCategory']]

       age     AgeGroup  hours_per_week WorkHoursCategory
0       39  Middle_Aged              40         Full_Time
1       50       Senior              13         Part_Time
2       38  Middle_Aged              40         Full_Time
3       53       Senior              40         Full_Time
4       28        Young              40         Full_Time
...    ...          ...             ...               ...
32556   27        Young              38         Full_Time
32557   40  Middle_Aged              40         Full_Time
32558   58       Senior              40         Full_Time
32559   22        Young              20         Part_Time
32560   52       Senior              40         Full_Time

[32561 rows x 4 columns]

In [26]:
#Apply a transformation (e.g., log transformation) to at least one skewed numerical feature and justify your choice.
print("Skewness of capital_gain:", df_final['capital_gain'].skew())

Skewness of capital_gain: 11.953847687699787

In [27]:
df_final['capital_gain_log'] = np.log1p(df_final['capital_gain'])  # log(1 + x) to handle zeros
df_final['capital_gain_log']

0        0.138416
1       -0.157731
2       -0.157731
3       -0.157731
4       -0.157731
           ...
32556   -0.157731
32557   -0.157731
32558   -0.157731
32559   -0.157731
32560    1.060711
Name: capital_gain_log, Length: 32561, dtype: float64

In [28]:
print("Skewness of capital_gain:", df_final['capital_gain_log'].skew())

Skewness of capital_gain: 5.90026949312501